name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 15.0.1
      - run: npm install
      - run: npm install -g prettier
      - run: npm run lint
      - run: npm run prettier
      - run: npm test
      - run: npm run build